<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-21T00:03:27 IST" name="Default suite" finished-at="2022-12-21T00:03:44 IST" duration-ms="17242">
    <groups>
    </groups>
    <test started-at="2022-12-21T00:03:27 IST" name="Default test" finished-at="2022-12-21T00:03:44 IST" duration-ms="17242">
      <class name="TestLogin.Login2Naukari">
        <test-method is-config="true" signature="Login2App()[pri:0, instance:TestLogin.Login2Naukari@9f116cc]" started-at="2022-12-21T00:03:27 IST" name="Login2App" finished-at="2022-12-21T00:03:36 IST" duration-ms="8763" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login2App -->
        <test-method signature="Login2app()[pri:0, instance:TestLogin.Login2Naukari@9f116cc]" started-at="2022-12-21T00:03:36 IST" name="Login2app" finished-at="2022-12-21T00:03:44 IST" duration-ms="8119" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at TestLogin.Login2Naukari.Login2app(Login2Naukari.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login2app -->
        <test-method is-config="true" signature="logout(org.testng.ITestResult)[pri:0, instance:TestLogin.Login2Naukari@9f116cc]" started-at="2022-12-21T00:03:44 IST" name="logout" finished-at="2022-12-21T00:03:44 IST" duration-ms="286" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Login2app status=FAILURE method=Login2Naukari.Login2app()[pri:0, instance:TestLogin.Login2Naukari@9f116cc] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- TestLogin.Login2Naukari -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
